type Event {
  id: String
  start: String!
  end: String!
  description: String
  title: String!
  created_at: String
  updated_at: String
  party_report: PartyReport
  room: [Room]!
  phone: String!
}

type Query {
  events: [Event]
  event(id: String): Event
  eventsFT(from: String!, to: String!): [Event]
}

input InputEvent {
  id: String
  start: String!
  end: String!
  description: String
  title: String!
  created_at: String
  updated_at: String
  party_report: InputPartyReport
  room: Room!
  phone: String!
}

type Mutation {
  createEvent(event: InputEvent): Boolean
}
