enum RegistrationStatus {
  PENDING
  ACCEPTED
  DENIED
}

type PartyReport {
  id: String
  responsible_name: String!
  responsible_number: String!
  responsible_email: String!
  co_responsible_name: String
  co_responsible_number: String
  co_responsible_email: String
  serving_permit: Boolean
  status: RegistrationStatus
  event: Event
}

input InputPartyReport {
  id: String
  responsible_name: String!
  responsible_number: String!
  responsible_email: String!
  co_responsible_name: String
  co_responsible_number: String
  co_responsible_email: String
  serving_permit: Boolean
  status: RegistrationStatus
}

type Query {
  party_reports: [PartyReport]
}
